version: '2'

services:
  app:
    build:
      context: ./
      dockerfile: php.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "ENVIRONMENT=development"
      - "DB_HOST=database"
      - "DB_NAME=wordpress"
      - "DB_USER=wordpress"
      - "DB_PASSWORD=secret"
  web:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    volumes:
      - ./vhost_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "13306:3306"
volumes:
  dbdata:
